---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install ansible-role-name package dependencies
  ansible.builtin.package:
    name: '{{ ansible-role-name_packages }}'
    state: present
  become: true
  register: install_ansible-role-name_packages
  when: ansible-role-name_packages is defined
  tags:
    - install
    - apt
    - update_cache
