---
- name: Create files ansible-role-name
  become: true
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: '{{ item.owner }}'
  with_items: '{{ _ansible-role-name_create_files | default({}) }}'
  when: _ansible-role-name_create_files is defined
