---
- name: Include vars by operating system.
  import_tasks: include_vars.yml

- name: Install dependencies
  import_tasks: dependences.yml
  when:
    - common_only_deploy == False

- name: Install Or Update Applications
  import_tasks: apps.yml
  when:
    - common_only_deploy == False

- name: Install Or Update files
  import_tasks: files.yml
  when:
    - common_only_deploy == False

- name: Install Or Update host
  import_tasks: host.yml
  when:
    - common_only_deploy == False

- name: implement configure
  import_tasks: configure.yml
  when:
    - common_only_deploy == False

- name: Implement task install
  import_tasks: install.yml
  when:
    - common_only_deploy == False

- name: Implement task templates
  import_tasks: templates.yml

- name: Implement task environment
  import_tasks: environment.yml

- name: Implement task post install
  import_tasks: post_install.yml
