---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    hostname: ubuntu1804
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu1804-ansible:latest}
    platform: linux/amd64
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
  - name: ubuntu2004
    hostname: ubuntu2004
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2004-ansible:latest}
    platform: linux/amd64
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
